### ISSUE TITLE
Extending OSD parsing tools

### ISSUE THREAD

**Issue by brownag** [ncss-tech/SoilKnowledgeBase#25]
RE: https://github.com/ncss-tech/soilDB/issues/186

After incorporation of new OSD products (the .csv files at least; do we need to track .sql too or could it be a build artifact?) address remaining issues from https://github.com/ncss-tech/parse-osd repo PRs and verify resolution in {SoilKnowledgeBase} products

 - [ ] extract additional data section and save ncss-tech/parse-osd#13 opened on May 13, 2020 by dylanbeaudette
 - [ ] old-style O horizons not parsed correcly ncss-tech/parse-osd#12 opened on Feb 10, 2020 by dylanbeaudette
 - [ ] add testing suite ncss-tech/parse-osd#11 opened on May 29, 2019 by dylanbeaudette
 - [ ] texture, pH, drainage class parsing is too greedy ncss-tech/parse-osd#10 opened on May 29, 2019 by dylanbeaudette
 - [ ] combination horizons described with 'and' ncss-tech/parse-osd#9 opened on Dec 20, 2018 by dylanbeaudette'
 - [ ] fill missing colors based on nearby horizons ncss-tech/parse-osd#8 opened on Mar 14, 2018 by dylanbeaudette
 - [ ] figure out how to find OSDs edited since last parse date ncss-tech/parse-osd#5 opened on Sep 15, 2017 by dylanbeaudette
 - [ ] some brief narratives are missing (93) ncss-tech/parse-osd#4 opened on Sep 2, 2017 by dylanbeaudette

**Comment by dylanbeaudette** [comment]
Updates:
  * I'm almost done adapting all of the old code related to fulltext searching. Once that is done, I'll move the SoilWeb prep code / results over to the SoilWeb-data repository. This includes everything related to `fetchOSD` and the fulltext search.
  * I'm planning to move the soil color stuff to a different repository soon

**Comment by dylanbeaudette** [comment]
Quick update, all of the code used to prep SoilWeb related data has been moved over to SoilWeb-data. Relying on OSDregistry and SKB to do all of the parsing work.
